### ISSUE TITLE
请问一下大哥 

### ISSUE THREAD

**Issue by mingzizenmequ** [chengshiwen/influx-tool#1]
spark  如何从influxDB中读取数据吗

**Comment by chengshiwen** [comment]
用[influxdb-java](https://github.com/influxdata/influxdb-java)，因为访问influxdb（包括库、客户端等）都是走http，所以spark目前要访问也只能用influxdb-java

**Comment by mingzizenmequ** [comment]
有相关示例代码吗   怎么将数据隐射到spark 的rdd中
